# MIT License
#
# Copyright (c) 2020-2022 F5, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#######
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threatstack-agent.name" . }}-config-args
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" . }}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config-args: {{ include "threatstack-agent.daemonset-RuntimeConfig" . }}
  kubernetes-api-config-args: enable_kubes_master 1 {{ .Values.apiReader.additionalRuntimeConfig }}
{{- if .Values.daemonset.customAuditRules }}
  custom-audit-rules-content: {{ toYaml .Values.daemonset.customAuditRules | indent 4 }}
{{- end }}
{{- if .Values.daemonset.customTsAuditdConfig }}
  custom-tsauditd-config-content: {{ toYaml .Values.daemonset.customTsAuditdConfig | indent 4 }}
{{- end }}
{{- if .Values.daemonset.customLuaFilter }}
  custom-luafilter-content: {{ toYaml .Values.daemonset.customLuaFilter | indent 4 }}
{{- end }}
